# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cryptic-io" # the base hostname & protocol for your site
permalink: :title/
paginate: 13

author: "Chris Dolphin"
keywords: 'developers, dev blog, tech industry, programming, development'

# Build settings
markdown: redcarpet
